version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: script/npm-install.sh
      runas: root
      timeout: 360
  ApplicationStart:
    - location: script/npm-start.sh
      runas: root
      timeout: 600
